name: cfstep-kubernetes-healthcheck
image: ./images/stethoscope.png
tag: 0.1.0
version: 0.1.0
description: Check Health of Kubernetes Deployment
categories:
- utility
keywords:
- healthcheck
- kubernetes
- linkerd
sources:
- https://github.com/codefresh-contrib/cfstep-kubernetes-healthcheck
maintainers:
- name: Dustin Van Buskirk
  email: dustinb@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/cfstep-msteams-notifier/master/images/icon-stethoscope.png
envs:
- name: CLUSTER
  type: required
  description: 'Kubernetes Context Name'
- name: DEPLOY_TIMEOUT
  type: optional
  description: '(seconds) Required for Kubernetes Type / Timeout for Deployment Completion, Default 120'
- name: DEPLOY_WAIT
  type: optional
  description: '(seconds) Between Deployment Checks, Default 5'
- name: DEPLOYMENT
  type: required
  description: 'Kubernetes Deployment/Statefulset Name'
- name: KUBE_CONFIG
  type: required
  description: 'Location of Kube Config file'
- name: METRIC_TIMEOUT
  type: optional
  description: '(seconds) Required for Linkerd Type / Time to wait for Prometheus to return metrics, Default 120'
- name: NAMESPACE
  type: required
  description: 'Kubernetes Namespace of Deployment'
- name: PROMETHEUS_URL
  type: optional
  description: 'Prometheus URL including protocol and port'
- name: THRESHOLD
  type: optional
  description: 'Required for Linkerd Type / Percentage represented in 1 - .01 (100% - 1%), Default 1'
- name: TOTAL
  type: optional
  description: '(seconds) Required for Linkerd Type / Total Time to Continue Testing, Default 300'
- name: TYPES
  type: required
  description: 'Type of Tests to Run comma delimited'
- name: WAIT
  type: required
  description: '(seconds) Wait between tests, Default 15'
